libwpe/cog: version bump to latest stable releases
Igalia/meta-webkit pull request #265
Opened 2021-05-03 14:53 UTC by Bastian-Krause

- libwpe: version bump 1.8.0 -> 1.10.0
- cog: version bump 0.8.0 -> 0.8.1

Merged patches were dropped, SRCREV_class-devupstream was set to the latest commitishes on the respective master branches.

2021-05-03 18:14 UTC, philn requested changes

2021-05-03 18:14 UTC, philn commented on recipes-browser/cog/cog_0.8.0.bb
> -           file://0002-egl-proc-address.h-add-a-license-header.patch \
Can the files be removed as well?

2021-05-04 08:02 UTC, Bastian-Krause commented on recipes-browser/cog/cog_0.8.0.bb
> -           file://0002-egl-proc-address.h-add-a-license-header.patch \
Oh of course, sorry about that.

2021-05-04 08:03 UTC, Bastian-Krause commented
Force-pushed:
- also dropped those cog patch files

2021-05-04 08:04 UTC, philn approved these changes

2021-05-08 01:26 UTC, merged

2021-05-08 01:26 UTC, clopez commented
Thanks!