wpewebkit: Bump to version 2.44.3
Igalia/meta-webkit pull request #505
Opened 2024-08-27 16:37 UTC by aperezdc

Changes:

* Decrease input notifications for gamepad inputs.
* Disable the gst-libav AAC decoder.
* Fix accelerated images dissapearing after scrolling.
* Fix mouse location in WebDriver when output device scaling is in effect.
* Fix several crashes and rendering issues.
* Fix the build on 32-bit ARM with USE_LIBWEBRTC enabled.
* Fix the build with ENABLE_WEBAUDIO disabled.
* Fix touch input event propagation.
* Fix video flickering with DMA-BUF sink.
* Fix web process cache suspend/resume when sandbox is enabled.
* Make gamepads visible on axis movements, and not only on button presses.
* Make user scripts and style sheets visible in the Web Inspector.
* Undeprecate console message API and make it available in 2022 API.
* Use optimized assembler BoringSSL modules with USE_LIBWEBRTC enabled.
* Use the geolocation portal where available, with the existing Geoclue as fallback if the portal is not usable.

Release notes:

  https://wpewebkit.org/release/wpewebkit-2.44.3.html https://wpewebkit.org/release/wpewebkit-2.44.2.html

This also includes the two patches mentioned in this e-mail to the mailing list as recommended over 2.44.3:

  https://lists.webkit.org/pipermail/webkit-gtk/2024-August/004002.html

2024-08-28 10:59 UTC, psaavedra requested changes
Looks like there is an issue with a patch


CmdError('quilt --quiltrc /home/bot/yocto-webkit-kirkstone/builds/raspberrypi3-mesa-wpe-2-44/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/2.44.3-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0004-Revert-Cherry-pick-272448.770-safari-7618-branch-6d3.patch
The next patch would delete the file JSTests/wasm/stress/many-calls-results-on-stack.js,
which does not exist!  Applying it anyway.
patching file JSTests/wasm/stress/many-calls-results-on-stack.js
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- rejects in file JSTests/wasm/stress/many-calls-results-on-stack.js
patching file Source/JavaScriptCore/wasm/WasmBBQJIT.cpp
Patch 0004-Revert-Cherry-pick-272448.770-safari-7618-branch-6d3.patch can be reverse-applied

2024-09-06 13:16 UTC, aperezdc commented
Switched the update to 2.44.4 instead, which already includes the two patches I was trying to include along with .3

2024-09-06 14:58 UTC, aperezdc commented
The failed CI jobs have the following error, which seems unrelated to the changes in this PR:

```
ERROR: Layer raspberrypi is not compatible with the core layer which only supports these series: scarthgap (layer is compatible with styhead)
```

2024-09-09 14:37 UTC, psaavedra commented
> The failed CI jobs have the following error, which seems unrelated to the changes in this PR:
> 
> ```
> ERROR: Layer raspberrypi is not compatible with the core layer which only supports these series: scarthgap (layer is compatible with styhead)
> ```

This should fix the error: https://github.com/Igalia/meta-webkit/commit/4f2f85c65f76c29ffa126458120ae54a6432b290

2024-09-09 20:05 UTC, aperezdc commented
> > The failed CI jobs have the following error, which seems unrelated to the changes in this PR:
> > ```
> > ERROR: Layer raspberrypi is not compatible with the core layer which only supports these series: scarthgap (layer is compatible with styhead)
> > ```
> 
> This should fix the error: [4f2f85c](https://github.com/Igalia/meta-webkit/commit/4f2f85c65f76c29ffa126458120ae54a6432b290)

Thanks! I have rebased the patch, so we should expect all the CI builds to pass now. I will prepare a separate PR updating WebKitGTK to 2.44.4, which was just released today.

2024-09-10 09:29 UTC, psaavedra commented
@aperezdc  all tests passed now. Feel free to land the change.

2024-09-10 09:30 UTC, psaavedra approved these changes
LGTM

2024-09-10 11:33 UTC, merged